import sys

def exit_error(msg):
	print(msg)
	sys.exit(1)
